### ISSUE TITLE
🚀 Example lectures checklist

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/courseware-as-code-example#1]
This issue lists the example lectures that will be added.

- [x] Using Markdown
- [x] Using LaTeX to Write Mathematical Equations
- [x] Embedding YouTube Videos and Other Media
- [x] Changing Site Configuration
- [x] Changing Themes

**Comment by KL13NT** [comment]
Closing as complete
